### ISSUE TITLE
Identify flaws in the usability of the Polis

### ISSUE THREAD

**Issue by luanguimaraesla** [cidadedemocratica/pushingtogether#22]
It is important to improve the new design on the mobile version.

**Comment by ut** [comment]
the mobile rendering of pol.is website a conversation consists of three major parts:

* vote to an opinion (=comment)
* see map (in realtime)
* write a comment

+ some minors: twitter + fb buttons, short explanation, footer with logo + imprint/tos

some ideas from henrique
* vote opinion + write a new one should stick together
* they should be clearly recongizeable as such
* map should stand separate

we could need an introduction mode, which shortly explain all elements of the screen (with help bubbles, switchable on/off)  (like http://zurb.com/playground/jquery-joyride-feature-tour-plugin )

**Comment by tallysmartins** [comment]
Great! I liked the three steps/screens separated. But we've to play with the iframe a little bit before we go deep with the coding.
